# Standard team code mappings across different sources
# Format: standard_code: [list of variations]
# Always use lowercase for consistency

arsenal: [ars]
aston_villa: [avl, villa]
bournemouth: [bou, afcb]
brentford: [bre, brf]
brighton: [bha, bri]
burnley: [bur]
chelsea: [che, cfc]
crystal_palace: [cry, pal]
everton: [eve]
fulham: [ful]
liverpool: [liv, lfc]
manchester_city: [mci, mnc, man_city]
manchester_united: [mun, man_utd]
newcastle: [new, nufc]
nottingham_forest: [nfo, not, forest]
sheffield_united: [shu, suf]
tottenham: [tot, thfc]
west_ham: [whu, wham]
wolves: [wol, wwfc]
luton: [lut, ltfc]
